#!/bin/bash

source config.sh

export MODULES_FILE_PREFIX=modules
export MODULES_FILE_SUFFIX=.zip
export MODULES_FILE_NAME=$MODULES_FILE_PREFIX$MODULES_FILE_SUFFIX

QUERY="for \$doc in xdmp:directory('/modules/') return fn:base-uri(\$doc)"

PROPERTIES="-DOUTPUT_PACKAGE=$MODULES_FILE_NAME -Dfile.encoding=UTF-8"
PROPERTIES="$PROPERTIES -DINPUT_CONNECTION_STRING=$MODULES_CONNECTION_STRING"
PROPERTIES="$PROPERTIES -DCOPY_COLLECTIONS=true"
PROPERTIES="$PROPERTIES -DCOPY_PERMISSIONS=false"
PROPERTIES="$PROPERTIES -DCOPY_PROPERTIES=true"
PROPERTIES="$PROPERTIES -DPRINT_CURRENT_RATE=true"
PROPERTIES="$PROPERTIES -DTHREADS=1"
# PROPERTIES="$PROPERTIES -DLOG_LEVEL=FINEST"

java -cp $CLASSPATH $PROPERTIES -DINPUT_QUERY="$QUERY" com.marklogic.ps.xqsync.XQSync""

rm $MODULES_FILE_NAME
mv $MODULES_FILE_PREFIX*$MODULES_FILE_SUFFIX $MODULES_FILE_NAME
