#!/bin/bash

source config.sh

QUERY="import module namespace jpm  = 'jpm:datamigration' at '/modules/JPM.DataMigration.xqy'; jpm:getXQSyncURIs()"

PROPERTIES="-DOUTPUT_PACKAGE=$OUTPUT_PACKAGE -Dfile.encoding=UTF-8"
PROPERTIES="$PROPERTIES -DINPUT_CONNECTION_STRING=$INPUT_CONNECTION_STRING"
PROPERTIES="$PROPERTIES -DCOPY_COLLECTIONS=true"
PROPERTIES="$PROPERTIES -DCOPY_PERMISSIONS=false"
PROPERTIES="$PROPERTIES -DCOPY_PROPERTIES=true"
PROPERTIES="$PROPERTIES -DPRINT_CURRENT_RATE=true"
PROPERTIES="$PROPERTIES -DTHREADS=$THREADS"
# PROPERTIES="$PROPERTIES -DLOG_LEVEL=FINEST"

java -cp $CLASSPATH $PROPERTIES -DINPUT_QUERY="$QUERY" com.marklogic.ps.xqsync.XQSync""
